---
title: " Effort Estimation"
author: "Doug & Laurie"
date: "25/05/2015"
output: ioslides_presentation
---

# SHORT-TERM CONTRACT 
## A MODELING APPROACH TO ESTIMATE OVERALL ATLANTIC EFFORT BY TIME-AREA STRATA (EFFDIS)

## Objectives

Develop a modeling approach to estimate overall Atlantic long-line, bait-boat and purse Seine by time-area strata, based on the data currently available at the ICCAT Secretariat.  This update of the EFFDIS dataset is critical for evaluation by-caught species.  

Development of a robust statistical modeling approach to estimate overall Atlantic fishing effort stratified by flag/fleet, gear, area (5ºx5º degree square grid), year and month (starting in 1950).  The current EFFDIS estimations will be updated for long-line using the new modeling approach, and then the  estimation procedure will be used for baitboat and purse-seine with the appropriate units of effort.  

## Recommendations 

SCECO made a series of recommendations for improving EFFDIS i.e.

+ Include seasonality 
+ Estimates of uncertainty
+ Cross-validation


## Workplan

+ Obtain all the relevant data 
+ Review the methods for EFFDIS estimation and write documented R code to mimic the current procedure. 
+ Develop a ‘strawman’ methodology for one fleet and seek feedback
+ Use an online SQL relational database and link to R

## Tasks
